# A simple utility play to remove a public key from the authorized key
# file for the ubuntu user
# You must pass in the entire line that you are adding
- hosts: all
  vars:
    owner: ubuntu
    keyfile: "/home/{{ owner }}/.ssh/authorized_keys"
  tasks:
    - fail: msg="You must pass in a public_key"
      when: public_key is not defined
    - command: mktemp
      register: mktemp
    # This command will fail if this returns zero lines which will prevent
    # the last key from being removed
    - shell: >
        grep -Fv '{{ public_key }}' {{ keyfile }} > {{ mktemp.stdout }}
    - shell: >
        while read line; do ssh-keygen -lf /dev/stdin <<<$line; done <{{ mktemp.stdout }}
        executable=/bin/bash
      register: keycheck
    - fail: msg="public key check failed!"
      when: keycheck.stderr != ""
    - command: cp {{ mktemp.stdout }} {{ keyfile }}
    - file: >
        path={{ keyfile }}
        owner={{ owner }}
        mode=0600
    - file: >
          path={{ mktemp.stdout }}
          state=absent
