- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: 'yes'
    openid_workaround: true
    EDXAPP_LMS_NGINX_PORT: '80'
    EDX_ANSIBLE_DUMP_VARS: true
    CERTS_DOWNLOAD_URL: 'http://192.168.33.10:18090'
    CERTS_VERIFY_URL: 'http://192.168.33.10:18090'
    edxapp_use_custom_theme: true
    edxapp_theme_name: 'dogeuniversity'
    edxapp_theme_source_repo: 'git://github.com/dhpollack/edx-theme.git'
    edxapp_theme_version: 'master'
    edx_platform_repo: 'https://github.com/dhpollack/edx-platform.git'
    edx_platform_version: 'master'
    edx_ansible_source_repo: 'https://github.com/dhpollack/configuration.git'
    configuration_version: 'master'
    DUMMY_VAR: true
  vars_files:
    - "group_vars/all"
  roles:
    - edx_ansible
    - user
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - ora
      - forum
      - xqueue
      - certs
      nginx_default_sites:
      - lms
      - cms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - demo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - ora
    - certs
    - edx_ansible
